broadcast/urls.py
from django.conf.urls import url

from broadcast import views

urlpatterns = [
    # ex: /broadcast/login
    url(r'^$', views.login, name='index'),
    # ex: /broadcast/login
    url(r'^login/$', views.login, name='login'),
    # ex: /broadcast/00110001/
    url(r'^success/$', views.check, name='check'),
    # ex: /broadcast/new_apply
    url(r'^new_apply/$', views.new_apply_html, name='new_apply_html'),

    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^broadcast/', include('broadcast.urls', namespace='broadcast')),
]

polls/urls.py
from django.conf.urls import url

from polls import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

broadcast/models.py
from django.db import models

# Create your models here.

class Areas(models.Model):
    area_name = models.CharField(max_length=100)
    area_desc = models.CharField(max_length=200)
    def __unicode__(self):
        return self.area_name

class Employees(models.Model):
    employee_id = models.CharField(max_length=8)
    employee_name = models.CharField(max_length=50)
    employee_pwd = models.CharField(max_length=200)
    def __unicode__(self):
        return self.employee_id + ": " + self.employee_name

class TimeList(models.Model):
    list_name = models.CharField(max_length=10)
    def __unicode__(self):
        return self.list_name

class ApplyInfos(models.Model):
    area_id = models.ForeignKey(Areas)
    employee_id = models.ForeignKey(Employees)
    apply_name = models.CharField(max_length=100)
    apply_date = models.DateTimeField('date apply')
    play_date = models.DateField('date play')
    play_time = models.ForeignKey(TimeList)
    file_path = models.CharField(max_length=300)
    apply_stage = models.IntegerField(default=0)
    def __unicode__(self):
        return self.apply_name + str(self.play_date) + str(self.play_time)

polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

broadcast/views.py
from django.shortcuts import get_object_or_404, render, render_to_response

# Create your views here.

from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse

from broadcast.models import Areas, Employees, TimeList, ApplyInfos
from polls.models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#	output = ', '.join([p.question_text for p in latest_question_list])
#	return HttpResponse(output)
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
		'lastest_question_list': latest_question_list,
	})
    return HttpResponse(template.render(context))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
#    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
#    response = "You're looking at the results of question %s."
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
#    return HttpResponse(response % question_id)

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
#    return HttpResponse("You're voting on question %s." % question_id)

def login(request):
    return render(request, 'broadcast/login.html')

def check(request):
    if request.method == 'POST':
#        uf = UserForm(request.POST)
#        if uf.is_valid():
        #Get User ID and PWD from <form>
        userid = request.POST['userid'].strip()
        password = request.POST['password'].strip()
        #Check the data from <form> with Database
        check_login = Employees.objects.filter(employee_id = userid, employee_pwd = password)
        if check_login:
            emp = Employees.objects.get(employee_id = userid)
            apin = ApplyInfos.objects.filter(employee_id = userid)
            return render_to_response('broadcast/success.html', {'user': emp, 'apins': apin})
        else:
            return HttpResponseRedirect(reverse('broadcast:login'))

#    return render_to_response('broadcast/success.html',{'username':username})
#    else:
#        uf = UserForm()
#    return render_to_response('broadcast/login.html')
#    return HttpResponseRedirect(reverse('broadcast:success', args=(p.id,)))
#    return render(request, 'broadcast/success.html',{'username':userid})
    return render(request, 'broadcast/success.html', {'userid':userid})

def new_apply_html(request):
    return render(request, 'broadcast/login.html')

def new_apply(request):
    
    from blog.models import Blog
    b = Blog(name='Beatles Blog', tagline='All the latest Beatles news.')
    b.save()

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse

from polls.models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
#    template = loader.get_template('polls/index.html')
#    context = RequestContext(request, {
#        'latest_question_list': latest_question_list,
#    })
#    return HttpResponse(template.render(context))
    
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
#    response = "You're looking at the results of question %s."
#    return HttpResponse(response % question_id)

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

broadcast/templates/broadcast/detail.html
<!--
<h1>{{question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>

{% endfor %}


</ul>
-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
   
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

{% endfor %}

<input type="submit" value="Vote" />

</form>

broadcast/templates/broadcast/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<html>
<head>
<link rel="stylesheet" type="text/css" href="css/Login_style.css" />
<script type="text/javascript" src="Javascript/Login_javascript.js"></script>
</head>
<body>
<h2 align="center">SenPng 修改制作</h2>
<div class="login_frame"></div>
<div class="LoginWindow">
  <div>
    <form method="post" action="{% url 'broadcast:check' %}" onsubmit="return user_input()" class="login">
    {% csrf_token %}
    <p>
      <label for="login">帐号:</label>
      <input type="text" name="userid" id="userid" value="">
    </p>

    <p>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="">
    </p>

    <p class="login-submit">
      <button type="submit" class="login-button">登录</button>
    </p>

    </form>
    <p class="registration"><a href="#">注册</a></p>
  </div>
</div>

<div id="timeArea"><script> LoadBlogParts();</script></div>

<div style="text-align:center;">
<p>来源:<a href="http://www.mycodes.net/" target="_blank">源码之家</a></p>
</div>

</body>
</html>

broadcast/templates/broadcast/new_apply_html.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html" />
	<meta charset="UTF-8"/>
	<link type="text/css" rel="stylesheet" href="calendar.css" >
	<script type="text/javascript" src="calendar.js" ></script>  
	<script type="text/javascript" src="calendar-zh.js" ></script>
	<script type="text/javascript" src="calendar-setup.js"></script>

</head>

<body>
	<from action="" method="POST">
		<p>考试科目：<input type="text" name="subject">
		<p>考试日期：<input type="text" id="EntTime" name="EntTime" onclick="return showCalendar('EntTime', 'y-mm-dd');"  />
		<p>考试时间：
		<div>
			<input type="radio" name="time" value="08">08:00
			<input type="radio" name="time" value="10">10:00
			<input type="radio" name="time" value="13">13:30
			<input type="radio" name="time" value="15">15:30
			<input type="radio" name="time" value="18">18:00<br>
		</div>
		<p>放音区域：<br>
		<div>
			<input type="checkbox" name="area" value="B2">B区2层
			<input type="checkbox" name="area" value="B3">B区3层
			<input type="checkbox" name="area" value="B4">B区4层
			<input type="checkbox" name="area" value="B5">B区5层
			<input type="checkbox" name="area" value="B6">B区6层<br>
			<input type="checkbox" name="area" value="C2">C区2层
			<input type="checkbox" name="area" value="C3">C区3层
			<input type="checkbox" name="area" value="C4">C区4层
			<input type="checkbox" name="area" value="C5">C区5层
			<input type="checkbox" name="area" value="C6">C区6层
		</div>
		<p>音频文件：
		<div>
			<input type="file">
			<input type="submit" value="上传音频文件">
		<p>音频文件地址：
		</div>
		<p><input type="submit" value="确认">

	</form>
</body>
</html>

broadcast/templates/broadcast/success.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
</head>
<body>

    <h1>恭喜{{ user.employee_id }},登录成功！</h1>
    <h2>{{apins}}<h2>

    <form action="{% url 'broadcast:new_apply_html'}" method="POST">
    {% csrf_token %}
    	<input type="submit" value="New Apply"/>
    </form>
    	
</form>
</body>
</html>

polls/templates/html5_login_2/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录界面</title>

<link rel="stylesheet" type="text/css" href="css/style.css" />
<link rel="stylesheet" type="text/css" href="css/animate.css" />

<script type="text/javascript" src="js/login.js"></script>
<script type="text/javascript" src="js/jquery.min.js"></script>	  
	  
</head>
 
<body>
	
<canvas id="christmasCanvas" style="top: 0px; left: 0px; z-index: 5000; position: fixed; pointer-events: none;" width="1285" height="100%"></canvas>

<script type="text/javascript">
	 var snow = function() {
    if(1==1) {
      $("body").append('<canvas id="christmasCanvas" style="top: 0px; left: 0px; z-index: 5000; position: fixed; pointer-events: none;"></canvas>');
      var b = document.getElementById("christmasCanvas"), a = b.getContext("2d"), d = window.innerWidth, c = window.innerHeight;
      b.width = d;
      b.height = c;
      for(var e = [], b = 0;b < 70;b++) {
        e.push({x:Math.random() * d, y:Math.random() * c, r:Math.random() * 4 + 1, d:Math.random() * 70})
      }
      var h = 0;
      window.intervral4Christmas = setInterval(function() {
        a.clearRect(0, 0, d, c);
        a.fillStyle = "rgba(255, 255, 255, 0.6)";
        a.shadowBlur = 5;
        a.shadowColor = "rgba(255, 255, 255, 0.9)";
        a.beginPath();
        for(var b = 0;b < 70;b++) {
          var f = e[b];
          a.moveTo(f.x, f.y);
          a.arc(f.x, f.y, f.r, 0, Math.PI * 2, !0)
        }
        a.fill();
        h += 0.01;
        for(b = 0;b < 70;b++) {
          if(f = e[b], f.y += Math.cos(h + f.d) + 1 + f.r / 2, f.x += Math.sin(h) * 2, f.x > d + 5 || f.x < -5 || f.y > c) {
            e[b] = b % 3 > 0 ? {x:Math.random() * d, y:-10, r:f.r, d:f.d} : Math.sin(h) > 0 ? {x:-5, y:Math.random() * c, r:f.r, d:f.d} : {x:d + 5, y:Math.random() * c, r:f.r, d:f.d}
          }
        }
      }, 70)
    }
  }
  snow();
</script>

<h2 align="center">登陆界面</h2>

<div class="login_frame"></div>

<div class="LoginWindow">
	<div>
		<div class="login">
			<p><input type="text" name="id" id="id" placeholder="用户名" value=""></p>
			<p><input type="password" name="password" id="password" placeholder="密码" value=""></p>
			<p class="login-submit"><button type="submit" class="login-button" id ="submit">登录</button></p>
		</div>
	<p class="registration  btn" id="regiest"><a>快速注册</a></p>
	</div>
</div>
	

<div class="box">
	<div class="regiest">
		<p><input type="text" id="username" placeholder="用户名"></p>
		<p><input type="text" id="nickname" placeholder="昵称" ></p>
		<p><input type="password" id="password" placeholder="密码" ></p>
		<p><input type="password" id="finalPWD" placeholder="确认密码"></p>
		<div id="btn2">
			<ul>
				<li><input type="button" value="关闭" class="colse"/></li>
				<li><input type="button" value="提交" class="sumbmit"/></li>
			</ul>
		</div>
	</div>
</div>

<div id="timeArea"><script type="text/javascript">LoadBlogParts();</script></div>

<script type="text/javascript">
$(function(){
	$(".btn").click(function(){
	var left = ($(window).width()*(1-0.35)) /2;//box弹出框距离左边的额距离
	var height =  ($(window).height()*(1-0.5)) /2;
	
   $(".box").addClass("animated bounceIn").show().css({left:left,top:top});
   $(".opacity_bg").css("opacity","0.3").show();
   });
  
  
   $(".colse").click(function(){
	 
	var left=($(window).width()*(1-0.35))/2;
	var top=($(window).height()*(1-0.5))/2;
	$(".box").show().animate({
		width:"-$(window).width()*0.35",
		height:"-$(window).height()*0.5",
		left:"-"+left+"px",
		top:"-"+top+"px"
		},1000,function(){
			 var width1 = $(window).width()*0.35;
			 var height1 =$(window).height()*0.5;
			 console.log(width1);
			$(this).css({width:width1,height:height1}).hide();
		});

   });
});
</script>
<div style="text-align:center;">
<p>来源:<a href="http://www.mycodes.net/" target="_blank">源码之家</a></p>
</div>
</body>
</html>

polls/templates/html5_user_login/index.html
<html>
<!DOCTYPE html>
<html lang="en" class="no-js">

    <head>

        <meta charset="utf-8">
        <title>登录(Login)</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->
        <link rel="stylesheet" href="assets/css/reset.css">
        <link rel="stylesheet" href="assets/css/supersized.css">
        <link rel="stylesheet" href="assets/css/style.css">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="assets/js/html5.js"></script>
        <![endif]-->

    </head>

    <body>

        <div class="page-container">
            <h1>登录(Login)</h1>
            <form action="" method="post">
                <input type="text" name="username" class="username" placeholder="请输入您的用户名！">
                <input type="password" name="password" class="password" placeholder="请输入您的用户密码！">
                <input type="Captcha" class="Captcha" name="Captcha" placeholder="请输入验证码！">
                <button type="submit" class="submit_button">登录</button>
                <div class="error"><span>+</span></div>
            </form>
            <div class="connect">
                <p>快捷</p>
                <p>
                    <a class="facebook" href=""></a>
                    <a class="twitter" href=""></a>
                </p>
            </div>
        </div>
		
        <!-- Javascript -->
        <script src="assets/js/jquery-1.8.2.min.js" ></script>
        <script src="assets/js/supersized.3.2.7.min.js" ></script>
        <script src="assets/js/supersized-init.js" ></script>
        <script src="assets/js/scripts.js" ></script>

    </body>
<div style="text-align:center;">
<p>来源：<a href="http://www.mycodes.net/" title="源码之家" target="_blank">源码之家</a></p>
</div>
</html>


polls/templates/polls/detail.html
<!--
<h1>{{question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>

{% endfor %}


</ul>
-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}

<input type="submit" value="Vote" />

</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
	{% for question in latest_question_list %}
	    <li><a href="{% url 'polls:detail' question.id %}/">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>

{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/index_2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<html>
<head>
<link rel="stylesheet" type="text/css" href="css/Login_style.css" />
<script type="text/javascript" src="Javascript/Login_javascript.js"></script>
</head>
<body>
<h2 align="center">SenPng 修改制作</h2>
<div class="login_frame"></div>
<div class="LoginWindow">
  <div>
    <form method="post" action="#" onsubmit="return user_input()" class="login">
    <p>
      <label for="login">帐号:</label>
      <input type="text" name="id" id="id" value="">
    </p>

    <p>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="">
    </p>

    <p class="login-submit">
      <button type="submit" class="login-button">登录</button>
    </p>

    </form>
    <p class="registration"><a href="#">注册</a></p>
  </div>
</div>

<div id="timeArea"><script> LoadBlogParts();</script></div>

<div style="text-align:center;">
<p>来源:<a href="http://www.mycodes.net/" target="_blank">源码之家</a></p>
</div>

</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>